# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dist_cartogram_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DistCartogramDialogBase(object):
    def setupUi(self, DistCartogramDialogBase):
        DistCartogramDialogBase.setObjectName("DistCartogramDialogBase")
        DistCartogramDialogBase.resize(723, 649)
        self.button_box = QtWidgets.QDialogButtonBox(DistCartogramDialogBase)
        self.button_box.setGeometry(QtCore.QRect(430, 600, 251, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.label_5 = QtWidgets.QLabel(DistCartogramDialogBase)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 701, 31))
        self.label_5.setObjectName("label_5")
        self.gridLayoutWidget = QtWidgets.QWidget(DistCartogramDialogBase)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 60, 691, 551))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pointLayerComboBox = gui.QgsMapLayerComboBox(self.gridLayoutWidget)
        self.pointLayerComboBox.setMinimumSize(QtCore.QSize(450, 0))
        self.pointLayerComboBox.setObjectName("pointLayerComboBox")
        self.gridLayout.addWidget(self.pointLayerComboBox, 1, 1, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.doubleSpinBox.setMinimum(0.8)
        self.doubleSpinBox.setMaximum(5.0)
        self.doubleSpinBox.setProperty("value", 1.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.matrixQgsFileWidget = gui.QgsFileWidget(self.gridLayoutWidget)
        self.matrixQgsFileWidget.setMinimumSize(QtCore.QSize(450, 0))
        self.matrixQgsFileWidget.setMaximumSize(QtCore.QSize(16777215, 39))
        self.matrixQgsFileWidget.setObjectName("matrixQgsFileWidget")
        self.gridLayout.addWidget(self.matrixQgsFileWidget, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.mFieldComboBox = gui.QgsFieldComboBox(self.gridLayoutWidget)
        self.mFieldComboBox.setObjectName("mFieldComboBox")
        self.gridLayout.addWidget(self.mFieldComboBox, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.backgroundLayerComboBox = gui.QgsMapLayerComboBox(self.gridLayoutWidget)
        self.backgroundLayerComboBox.setMinimumSize(QtCore.QSize(450, 0))
        self.backgroundLayerComboBox.setObjectName("backgroundLayerComboBox")
        self.gridLayout.addWidget(self.backgroundLayerComboBox, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.refFeatureComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.refFeatureComboBox.setObjectName("refFeatureComboBox")
        self.gridLayout.addWidget(self.refFeatureComboBox, 4, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBoxResult = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxResult.setEnabled(False)
        self.checkBoxResult.setCheckable(True)
        self.checkBoxResult.setChecked(True)
        self.checkBoxResult.setTristate(False)
        self.checkBoxResult.setObjectName("checkBoxResult")
        self.verticalLayout.addWidget(self.checkBoxResult)
        self.checkBoxImagePointLayer = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxImagePointLayer.setObjectName("checkBoxImagePointLayer")
        self.verticalLayout.addWidget(self.checkBoxImagePointLayer)
        self.checkBoxSourceGrid = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxSourceGrid.setObjectName("checkBoxSourceGrid")
        self.verticalLayout.addWidget(self.checkBoxSourceGrid)
        self.checkBoxTransformedGrid = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxTransformedGrid.setObjectName("checkBoxTransformedGrid")
        self.verticalLayout.addWidget(self.checkBoxTransformedGrid)
        self.gridLayout.addLayout(self.verticalLayout, 7, 1, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_2.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBox_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.doubleSpinBox_2.setProperty("value", 1.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 6, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 1)
        self.button_box.raise_()
        self.label_5.raise_()
        self.gridLayoutWidget.raise_()
        self.checkBoxTransformedGrid.raise_()
        self.checkBoxImagePointLayer.raise_()
        self.checkBoxResult.raise_()

        self.retranslateUi(DistCartogramDialogBase)
        self.button_box.accepted.connect(DistCartogramDialogBase.accept)
        self.button_box.rejected.connect(DistCartogramDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(DistCartogramDialogBase)

    def retranslateUi(self, DistCartogramDialogBase):
        _translate = QtCore.QCoreApplication.translate
        DistCartogramDialogBase.setWindowTitle(_translate("DistCartogramDialogBase", "DistCartogram"))
        self.label_5.setText(_translate("DistCartogramDialogBase", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Distance cartogram creation </span></p></body></html>"))
        self.label_6.setText(_translate("DistCartogramDialogBase", "Grid precision"))
        self.label_2.setText(_translate("DistCartogramDialogBase", "Point layer"))
        self.label_7.setText(_translate("DistCartogramDialogBase", "Displacement factor"))
        self.label_3.setText(_translate("DistCartogramDialogBase", "Time matrix"))
        self.label_8.setText(_translate("DistCartogramDialogBase", "Point layer id field"))
        self.label.setText(_translate("DistCartogramDialogBase", "Background layer"))
        self.label_4.setText(_translate("DistCartogramDialogBase", "Reference feature"))
        self.checkBoxResult.setText(_translate("DistCartogramDialogBase", "Transformed layer"))
        self.checkBoxImagePointLayer.setText(_translate("DistCartogramDialogBase", "Image point layer"))
        self.checkBoxSourceGrid.setText(_translate("DistCartogramDialogBase", "Source grid"))
        self.checkBoxTransformedGrid.setText(_translate("DistCartogramDialogBase", "Transformed grid"))
        self.label_9.setText(_translate("DistCartogramDialogBase", "Output"))

from qgis import gui
